### PR TITLE
Ft login ch4

### PR DESCRIPTION
**Pull request by sanya-kenneth**
@frankopkusianwar @AtamaZack @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @kalsmic @mwinel

### What does this PR do?
- implements login to the api using UIs

### CODE REVIEW

**Comment by kalsmic** [comment]
@sanya-kenneth, Please remember to change the API server from localhost to the one on Heroku.

**Comment by reifred** [comment]
@sanya-kenneth, My issue is also about changing the API server to the one on Heroku

**Comment by sanya-kenneth** [comment]
Thanks guys. I will not forget to.

**Comment by kalsmic** [comment]
@sanya-kenneth, when you change the server, let us know so that we can fully test this feature.

**Pull request merged**
